// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectInputFiles() {
  return window['go']['main']['App']['SelectInputFiles']();
}

export function SelectOutputFolder() {
  return window['go']['main']['App']['SelectOutputFolder']();
}

export function StartProcessing(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartProcessing'](arg1, arg2, arg3);
}

export function StopProcessing() {
  return window['go']['main']['App']['StopProcessing']();
}
