// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectInputFolder():Promise<string>;

export function SelectOutputFile(arg1:string):Promise<string>;

export function StartProcessing(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StopProcessing():Promise<void>;
