// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectInputFolder() {
  return window['go']['main']['App']['SelectInputFolder']();
}

export function SelectOutputFile(arg1) {
  return window['go']['main']['App']['SelectOutputFile'](arg1);
}

export function StartProcessing(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartProcessing'](arg1, arg2, arg3);
}

export function StopProcessing() {
  return window['go']['main']['App']['StopProcessing']();
}
