// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectInputFiles():Promise<Array<string>>;

export function SelectOutputFolder():Promise<string>;

export function StartProcessing(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function StopProcessing():Promise<void>;
